//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odec.Server.Model.User.Migrations.Normalized {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserExtMigrationScripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal UserExtMigrationScripts() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("odec.CP.Server.Model.User.Migrations.Normalized.UserExtMigrationScripts", typeof(UserExtMigrationScripts).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  DECLARE @CurrentMigration [nvarchar](max)
        ///begin tran
        ///IF @CurrentMigration IS NULL
        ///    SET @CurrentMigration = &apos;0&apos;
        ///
        ///IF @CurrentMigration &lt; &apos;201603192332523_NormalizedUserExtInitial&apos;
        ///BEGIN
        ///	IF  NOT EXISTS (SELECT * FROM sys.objects 
        ///	WHERE object_id = OBJECT_ID(N&apos;[dbo].[ContactPhones]&apos;) AND type in (N&apos;U&apos;))
        ///	begin
        ///		CREATE TABLE [dbo].[ContactPhones] (
        ///			[PhoneId] [int] NOT NULL,
        ///			[ContactId] [int] NOT NULL,
        ///			CONSTRAINT [PK_dbo.ContactPhones] PRIMARY KEY ([PhoneId], [ContactId])
        ///		)
        ///		CREAT [rest of string was truncated]&quot;;.
        /// </summary>
        public static string InitialNormalizedUserExt {
            get {
                return ResourceManager.GetString("InitialNormalizedUserExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  
        ///begin tran
        ///if not exists( select top 1 1 from dbo.AspNetRoles where Name like &apos;CUSTOMER&apos;)
        ///begin
        ///INSERT INTO dbo.AspNetRoles (Name,Scope,InRoleId)
        ///values (&apos;Customer&apos;,&apos;WebSite&apos;,null)
        ///end
        ///if not exists( select top 1 1 from dbo.AspNetRoles where Name like &apos;Admin&apos;)
        ///begin
        ///INSERT INTO dbo.AspNetRoles (Name,Scope,InRoleId)
        ///values (&apos;Admin&apos;,&apos;WebSite&apos;,null)
        ///end
        ///if not exists( select top 1 1 from dbo.AspNetRoles where Name like &apos;Crafter&apos;)
        ///begin
        ///INSERT INTO dbo.AspNetRoles (Name,Scope,InRoleId)
        ///values (&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RolesSeed {
            get {
                return ResourceManager.GetString("RolesSeed", resourceCulture);
            }
        }
    }
}
